import img from "./structu full.svg";

export const clubsData = [
  {
    id: 1,
    name: "Sport Klubi",
    image: img,
    tutor: "Mamajonov Iqboljon",
    info: "Sog'lom turmush tarzini targ'ib qilish va sport mashg'ulotlarini tashkil etish.",
    fields: ["Futbol", "Basketbol", "Tennis", "Yoga"],
  },
  {
    id: 2,
    name: "Yosh Olimlar Markazi",
    image: img,
    tutor: "Turobov Ilhom",
    info: "Ilmiy tadqiqotlar va innovatsion loyihalarni qo'llab-quvvatlash.",
    fields: [
      "Fizika",
      "Sun'iy intellekt tadqiqotlari",
      "Innovatsiyalar",
      "Matematika",
    ],
  },
  {
    id: 3,
    name: "Yosh Akademiklar va Innovatorlar",
    image: img,
    tutor: "Rahimov Dilshod",
    info: "Ilmiy qiziqishlarga ega talabalar uchun platforma.",
    fields: ["Tadqiqot", "Tanqidiy fikrlash", "Ilmiy munozaralar"],
  },
  {
    id: 4,
    name: "Matematika Klubi",
    image: img,
    tutor: "Turdiyev Shodmon",
    info: "Murakkab masalalarni yechish va musobaqalarda ishtirok etish.",
    fields: ["Algebra", "Geometriya", "Statistika"],
  },
  {
    id: 5,
    name: "Sun'iy Intellekt va Kibersport",
    image: img,
    tutor: "Fayzullayev Jamshid",
    info: "Texnologiyalar va kompyuter o'yinlari musobaqalariga e'tibor qaratish.",
    fields: [
      "Sun'iy intellekt rivojlantirish",
      "O'yin strategiyasi",
      "Dasturlash",
    ],
  },
  {
    id: 6,
    name: "San'at, Drama va Teatr",
    image: img,
    tutor: "Saidaliyeva Nilufar",
    info: "Ijodkorlikni rivojlantirish va teatr san'atini o'rganish.",
    fields: ["Aktrisa/aktyorlik", "Rejissura", "Ssenariy yozish", "Raqs"],
  },
  {
    id: 7,
    name: "Dizayn Klubi",
    image: img,
    tutor: "Yo‘ldosheva Nodira",
    info: "Grafik va zamonaviy dizayn san'atini o'rganish va loyihalar yaratish.",
    fields: ["Grafik dizayn", "UI/UX", "Illyustratsiya", "Animatsiya"],
  },
  {
    id: 8,
    name: "Yosh Diplomatlar Klubi",
    image: img,
    tutor: "Nasimov Sunnatilla",
    info: "Muzokaralar va diplomatik ko'nikmalarni rivojlantirish.",
    fields: ["Xalqaro munosabatlar", "Jamoat oldida so'zlash", "Muzokaralar"],
  },
  {
    id: 9,
    name: "Chet Tillar Klubi",
    image: img,
    tutor: "Axmedova Nilufar",
    info: "Chet tillarni o'rganish va amaliy qo'llash imkonini yaratish.",
    fields: ["Ingliz tili", "Ispan tili", "Fransuz tili", "Nemis tili"],
  },
  {
    id: 10,
    name: "Universitet Podcast Klubi",
    image: img,
    tutor: "Abduraxmonov Abduqodir",
    info: "Audio kontent yaratish va ijodiy muloqotlarni rivojlantirish.",
    fields: ["Podkast yaratish", "Hikoya qilish", "Intervyu olish"],
  },
];
