export const khanAcademyCourseParamsData = [
  {
    id: 1,
    courseName: 'Boshlang`ich matematika',
    descr: `Matematika - bu hayotimiz davomida eng kerak bo'ladigan fan hisobkanadi. Qaysi sohani tanlamang, matematik bilimlarsiz qiyinchiliklarga yo'riqasiz. Aynan shu uchun matematikani biz bilan maroqli o'rganing!`,
    duration: '6 soat 10 min',
    level: '1-4-sinflar uchun',
  },
  {
    id: 2,
    courseName: 'Arifmetika',
    descr: `Matematika - bu hayotimiz davomida eng kerak bo'ladigan fan hisobkanadi. Qaysi sohani tanlamang, matematik bilimlarsiz qiyinchiliklarga yo'riqasiz. Aynan shu uchun matematikani biz bilan maroqli o'rganing!`,
    duration: '5 soat 37 min',
    level: '5-6-sinflar uchun',
  },
  {
    id: 3,
    courseName: 'Algebra 1',
    descr: `Matematika - bu hayotimiz davomida eng kerak bo'ladigan fan hisobkanadi. Qaysi sohani tanlamang, matematik bilimlarsiz qiyinchiliklarga yo'riqasiz. Aynan shu uchun matematikani biz bilan maroqli o'rganing!`,
    duration: '6 soat 15 min',
    level: '7-8-sinflar uchun',
  },
  {
    id: 4,
    courseName: 'Algebra 2',
    descr: `Matematika - bu hayotimiz davomida eng kerak bo'ladigan fan hisobkanadi. Qaysi sohani tanlamang, matematik bilimlarsiz qiyinchiliklarga yo'riqasiz. Aynan shu uchun matematikani biz bilan maroqli o'rganing!`,
    duration: '7 soat 9 min',
    level: '9-11-sinflar uchun',
  },
  {
    id: 5,
    courseName: 'Geometriya asosolari',
    descr: `Matematika - bu hayotimiz davomida eng kerak bo'ladigan fan hisobkanadi. Qaysi sohani tanlamang, matematik bilimlarsiz qiyinchiliklarga yo'riqasiz. Aynan shu uchun matematikani biz bilan maroqli o'rganing!`,
    duration: '6 soat 51 min',
    level: '5-7-sinflar uchun',
  },
  {
    id: 6,
    courseName: 'Geometriya',
    descr: `Matematika - bu hayotimiz davomida eng kerak bo'ladigan fan hisobkanadi. Qaysi sohani tanlamang, matematik bilimlarsiz qiyinchiliklarga yo'riqasiz. Aynan shu uchun matematikani biz bilan maroqli o'rganing!`,
    duration: '8 soat 1 min',
    level: '8-10-sinflar uchun',
  },
  {
    id: 7,
    courseName: 'Trigonometriya',
    descr: `Matematika - bu hayotimiz davomida eng kerak bo'ladigan fan hisobkanadi. Qaysi sohani tanlamang, matematik bilimlarsiz qiyinchiliklarga yo'riqasiz. Aynan shu uchun matematikani biz bilan maroqli o'rganing!`,
    duration: '4 soat 22 min',
    level: '9-11-sinflar uchun',
  },
  {
    id: 8,
    courseName: 'Matematik analiz asosolari',
    descr: `Matematika - bu hayotimiz davomida eng kerak bo'ladigan fan hisobkanadi. Qaysi sohani tanlamang, matematik bilimlarsiz qiyinchiliklarga yo'riqasiz. Aynan shu uchun matematikani biz bilan maroqli o'rganing!`,
    duration: '5 soat 58 min',
    level: '11-sinf uchun',
  },
  {
    id: 9,
    courseName: 'Chiziqli algebra',
    descr: `Matematika - bu hayotimiz davomida eng kerak bo'ladigan fan hisobkanadi. Qaysi sohani tanlamang, matematik bilimlarsiz qiyinchiliklarga yo'riqasiz. Aynan shu uchun matematikani biz bilan maroqli o'rganing!`,
    duration: '4 soat 46 min',
    level: '11-sinf uchun',
  },
];
